### ISSUE TITLE
【RFC】0.2 TODO

### ISSUE THREAD

**Issue by zhuxudong** [oasis-engine/playground#5]
**希望以后的每个里程碑，大家能将自己新增的，优化的，创新的，新颖的idea，体现在 [游乐场](https://github.com/oasis-engine/playground) 里。

> *因为是游乐场的第一次迁移，所以这里着重说一下开发重点，以后的里程碑就不再赘述了。*
* 以后统一在 [外网仓库](https://github.com/oasis-engine/playground) 开发，大家记得切换账号，并按照 Github workflow 提交代码。
* 代码要重点突出demo部分，尽量封装与demo无关的代码。
* 新增项目运行 `tnpm run add-demo`即可。
* 本地link开发使用`tnpm run dev:vite`,线上版本umd开发使用 `tnpm run dev`。
* 优秀的模型，纹理等资源，可以共享到 [Basement - Oasis Hub](https://yuyan-base.antfin-inc.com/OasisHub/file/detail/5fab5817c3dc8a0547aa9325?page=1&type=others)

### 0.2 TodoList
- [x] BufferGeometry @chenmo.gl 
- [x] 自定义 shader @chenmo.gl @shensi.zxd 
- [x] 视频纹理 @shensi.zxd 
- [x] 环境反射探针（cube renderTarget） @shensi.zxd 
- [x] 视锥剔除 @shensi.zxd  
- [x] 动画渐变过渡 @shensi.zxd 
- [x] 相机 cullingMask @kevin.hs
